

export const sliderItems = [
    {
      id: 1,
      img: "https://i.ibb.co/DfDjNQG/TRUFFES-NOIRES.png" ,
      title: "Domaine des 3 Lys	Rouge - Les Truffes Noires",
      subtitle: "AOP Côtes du Rhône",
      desc: "60% Syrah + 30% Grenache + 10% Carignan",
      bg: "fffff",
    
    },
    {
      id: 2,
      img: "https://i.ibb.co/qdNqs0Y/Chateau-Saint-Be-ne-zet-Moulin-Baguet.png",
      title: "Moulin Baguet Blanc",
      subtitle: "AOP COSTIERES DE NÎMES",
      desc: "VIOGNIER + 30% GRENACHE BLANC + VERMENTINO",
      bg: "transparent",
    },
    {
      id: 3,
      img: "https://i.ibb.co/HGDYZX5/Les-caprices-de-Lola.png",
      title: "Les Caprices de Lola Rosé",
      subtitle: "AOP COSTIERES DE NÎMES",
      desc: "50%  GRENACHE + 50% SYRAH",
      bg: "transparent",
    },
  ];

  export const wineList = [
    {
      id: 0,
      img: "https://i.ibb.co/JxwdD9X/4-Chateau-Bellefontaine-rose.jpg",
      title: "Bellefontaine Prestige Rosé",
      subtitle: "AOP Costières de Nîmes",
      desc: "Druvorna skördas på natten för optimal kyla, krossas direkt efter och jäses mellan 16 - 18 °C. Ljus fin rosa färg. Vinet är elegant, doftar och smakar friskt med inslag av hallon, röda vinbär och persika. Serveras vid ca ca 8 -10 °C och passar som aperitif, till sparris, sallader och lättare kycklingrätter.",
      sort: "50%  GRENACHE NOIR + 40% SYRAH + 10% VIOGNIER",
      year: "2021",
      bg: "fffff",
      category: "rose",
    },
    {
      id: 1,
      img: "https://i.ibb.co/59Mr9Pq/3-Chateau-Bellefontaine-blanc.jpg",
      title: "Bellefontaine Prestige Blanc",
      subtitle: "AOP Costières de Nîmes",
      desc: "Druvorna skördas på natten för optimal kyla, krossas direkt efter och jäses mellan 16 - 18 °C. Vinet har en vacker lysande guldfärg. Det är ett torrt vin med inslag av saftiga gula stenfrukter, vit persika, aprikos och ett stänk av citrus vilket gör att vinet fungerar utmärkt med både fisk och ljusa kötträtter. Serveras vid ca 8 °C-10 °C och passar som aperitif, till sparris, sallader och lättare kycklingrätter.",
      sort: "50%  GRENACHE + 30% ROUSSANE + 20% GRENACHE",
      year: "2021",
      bg: "fbf0f4",
      category: "white",
    
    },
    {
      id: 2,
      img: "https://i.ibb.co/QXcL5YQ/Chateau-bellefontaine-Prestige.jpg",
      title: "Bellefontaine Prestige Rouge",
      subtitle: "AOP Costières de Nîmes",
      desc: "Intensiv röd lila färg. Generöst vin med inslag av mörka bär såsom körsbär, hallon, svarta vinbär med en fin underton av lakrits och viol. En ren smakexplosion i munnen. Serveras vid 16°C-18°C och passar till kötträtter, rätter med sås eller ost.",
      sort: "70%  SYRAH + 30% GRENACHE",
      year: "2020",
      bg: "fbf0f4",
      category: "red",
    
    },
    {
      id: 3,
      img: "https://i.ibb.co/xzczVGq/Les-fables-de-bellefontaine.jpg",
      title: "Les Fables de Bellefontaine Rouge",
      subtitle: "AOP Costières de Nîmes",
      desc: "Djup röd färg. Ett mycket elegant, komplext vin med aromer av mörka bär och mogna frukter. Vinet känns sammetslent i munnen med delikata toner av körsbär och mörk choklad. Ett mycket välbalanserat och elegant vin med inslag av mineraler och väl mogna tanniner med en lång härlig eftersmak. Vinet lagras på franskt ekfat under ca 15 månader.",
      sort: "60% Syrah + 40% Grenache Noir",
      year: "2016",
      bg: "fbf0f4",
      category: "red",
    
    },
    {
      id: 4,
      img: "https://i.ibb.co/w09s81S/Moulin-Baguet.jpg",
      title: "Moulin Baguet Rouge",
      subtitle: "AOP Costières de Nîmes",
      desc: "Ett generöst vin med bra substans och en balanserad struktur. En uttrycksfull smakpalett med härlig kryddighet och toner av körsbär och örter. Ett vin som växer med mat. Serveras vid  18°C till kötträtter, rätter med sås och ost.",
      sort: "70%  SYRAH + 30% GRENACHE",
      year: "2021",
      bg: "fcf1ed",
      category: "red",
    },
    {
        id: 5,
        img: "https://i.ibb.co/L52c4Y7/Chateau-Saint-Be-ne-zet-Moulin-Baguet.jpg",
        title: "Moulin Baguet Blanc",
        subtitle: "AOP Costières de Nîmes",
        desc: "Elegant, nyanserat vitt vin med guldiga nyanser. Mycket frisk smak med inslag av vita blommor, smör och stenfrukt såsom persika och aprikos. Serveras vid 8 °C-10 °C som aperitif, eller till rätter av fisk eller skaldjur eller sallader.",
        sort: "VIOGNIER + 30% GRENACHE BLANC + VERMENTINO",
        year: "2021",
        bg: "fffff",
        category: "white",
      },
      {
        id: 6,
        img: "https://i.ibb.co/b1gr4NC/Saint-be-ne-zet-Les-hauts-de-coste-Rive.jpg",
        title: "Les Hauts de Coste-Rives Rosé",
        subtitle: "AOP Costières de Nîmes",
        desc: "Elegant smak med inslag av fläder, citrus och röda bär. Ett fylligt vin som både är friskt och aromatiskt. Serveras vid 8-10 °C som sällskapsdryck, till rätter av fisk eller kyckling eller sallader.",
        sort: "50% GRENACHE + 50% SYRAH",
        year: "2021",
        bg: "fcf1ed",
        category: "rose",
      },
      {
        id: 7,
        img: "https://i.ibb.co/gt8dNrT/Les-caprices-de-Lola.jpg",
        title: "Les Caprices de Lola Rosé",
        subtitle: "AOP Costières de Nîmes",
        desc: "Blommigt och fruktigt vin med inslag av smultron och jordgubbe. Stort och lättdrucket vin med kvarstående aroma. Utmärkt sommar rosé som passar bra till kyckling, grillat kött och sallad. Serveras vid  8 °C-10 °C.",
        sort: "50%  GRENACHE + 50% SYRAH",
        year: "2020",
        bg: "fbf0f4",
        category: "rose",
      },
      {
        id: 8,
        img: "https://i.ibb.co/qDGkWTn/11-Preference-Merlot-Cabernet-Sauvignon.jpg",
        title: "Préférence IGP OC Rouge Merlot",
        subtitle: "AOP Costières de Nîmes",
        desc: "En mycket uttrycksfull smakpalett med härlig kryddighet och toner av svarta vinbär, körsbär, björnbär med en touch av ekfat med mineralitet och fina mjuka tanniner som ger bra struktur och lämnar en elegant strävhet. Serveras vid 18°C till rätter av lamm och nötkött.",
        sort: "50%  MERLOT + 50% CABERNET - SAUVIGNON",
        year: "2019",
        bg: "fffff",
        category: "red",
      },
      {
        id: 9,
        img: "https://i.ibb.co/4VhXDTr/5-Preference-Syrah-grenache.jpg",
        title: "Préférence IGP OC Rosé",
        subtitle: "AOP Costières de Nîmes",
        desc: "Fruktig, pärlande smak med inslag av persika och röda bär. En smak explosion på tungan. Serveras vid 8 °C-10 °C som sällskapsdryck, till rätter av fisk eller kyckling eller sallader.",
        sort: "50%  GRENACHE + 50% SYRAH",
        year: "2020",
        bg: "fcf1ed",
        category: "rose",
      },
      {
        id: 10,
        img: "https://i.ibb.co/k9qnR6X/1-Domaine-des-3-Lys-Tradition.jpg",
        title: "Domaine des 3 Lys	Rouge - Tradition",
        subtitle: "AOP Côtes du Rhône",
        desc: "Ett fylligt vin som har en intensiv rubinröd färg. Vinet erbjuder smaker av mogna hallon, björnbär,blåbär med inslag av blommiga detaljer såsom viol. Välsmakande med mjuka tanniner som avslutas i en mycket behaglig eftersmak. Serveras vid 16°C-18°C och passar särskilt bra till kötträtter gärna från grillen och ost.",
        sort: "40% Syrah + 40% Grenache + 20% Carignan",
        year: "2020",
        bg: "fcf1ed",
        category: "red",
        symbol: ""
      },
      {
        id: 11,
        img: "https://i.ibb.co/Y7tZcmD/TRUFFES-NOIRES.jpg",
        title: "Domaine des 3 Lys	Rouge - Les Truffes Noires",
        subtitle: "AOP Côtes du Rhône",
        desc: "Djup röd färg med intensiva, eleganta och kryddiga toner av mogna röda bär. Smakrikt vin med lång eftersmak. Vann guldmedalj i Paris och i Orange 2020.Serveras vid 16°C-18°C och passar till kötträtter, rätter med sås eller ost.",
        sort: "60% Syrah + 30% Grenache + 10% Carignan",
        year: "2019",
        bg: "fcf1ed",
        category: "red",
      },
      {
        id: 12,
        img: "https://i.ibb.co/pfLnL27/8-Chardonnay-Sensation.jpg",
        title: "Chardonnay Sensation Blanc",
        subtitle: "IGP OC CHARDONNAY",
        desc: "Vitt ljust vin med svaga guldiga nyanser. Uppfriskande, stor fyllighet, komplexitet och struktur med inslag av vita blommer honung och torkade frukter. Serveras vid 8°C-10°C som aperitif, eller till rätter av fisk eller skaldjur eller till smakrikare vegetariska rätter.",
        sort: "100% Chardonnay",
        year: "2021",
        bg: "fcf1ed",
        category: "white",
      },


  ];


